version: '3.0'

expectations:
  population_size: 50000

actions:

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  data_process:
    run: r:latest analysis/R/data_process.R
    needs: [extract]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed.rds
        data2: output/data/data_long_vax_dates.rds


  data_properties:
    run: r:latest analysis/R/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data*.txt

  data_matching:
    run: r:latest analysis/R/matching.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/data_vax_*.csv

  matching:
    run: python:latest analysis/matching.py
    needs: [data_matching]
    outputs:
      highly_sensitive:
        cases: output/matched/matched_cases.csv
        matches: output/matched/matched_matches.csv
        combined: output/matched/matched_combined.csv
        report: output/matched/matching_report.txt




  data_define_cohorts:
    run: r:latest analysis/R/data_define_cohorts.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/data/data_cohorts.rds
      moderately_sensitive:
        metadata: output/data/metadata*
        formula: output/data/list_formula.rds
        strata: output/data/list_strata.rds
        flow: output/data/flowchart*.csv



##############################################################################
##############################################################################
  ## VE in over 80s (over80s)
##############################################################################
##############################################################################

  data_stset:
    run: r:latest analysis/R/data_stset.R
    needs: [data_define_cohorts, data_process]
    outputs:
      highly_sensitive:
        data: output/data/data_*.rds

  data_properties_fixed:
    run: r:latest analysis/R/data_properties.R output/data/data_wide_fixed.rds output/data_properties
    needs: [data_stset]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_wide_fixed*.txt

  data_properties_tte:
    run: r:latest analysis/R/data_properties.R output/data/data_wide_tte.rds output/data_properties
    needs: [data_stset]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data_wide_tte*.txt

  descr_table1:
    run: r:latest analysis/R/table1.R
    needs: [data_define_cohorts, data_stset]
    outputs:
      moderately_sensitive:
        table1: output/descr/tables/table*

  descr_events:
    run: r:latest analysis/R/plot_status_over_time.R
    needs: [data_define_cohorts, data_stset]
    outputs:
      moderately_sensitive:
        plots: output/descr/plots/*.svg
        tables: output/descr/tables/*.csv



#######################################
 ## COMPARATIVE EFFECTIVENESS MODELS:
#######################################

  cemodels_cox_postest_compare_all:
    run: r:latest analysis/R/ce/model_cox.R postest all
    needs: [data_define_cohorts, data_stset]
    outputs:
      highly_sensitive:
        models: output/postest/all/*/modelcox*.rds

  cereport_postest_compare_all:
    run: r:latest analysis/R/ce/report_cox.R postest all
    needs: [data_define_cohorts, cemodels_cox_postest_compare_all]
    outputs:
      moderately_sensitive:
        plots: output/postest/all/*.svg
        tables: output/postest/all/*.csv

