version: '3.0'

expectations:
  population_size: 100000

actions:


  design:
    run: r:latest analysis/process/design.R
    outputs:
      moderately_sensitive:
        metadata: output/data/metadata*

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  data_process:
    run: r:latest analysis/process/data_process.R
    needs: [extract]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed.rds
        data2: output/data/data_long_vax_dates.rds

  data_properties:
    run: r:latest analysis/process/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        datasummary: output/data_properties/data*.txt

  data_selection:
    run: r:latest analysis/process/data_selection.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data_allvax: output/data/data_cohort_allvax.rds
        data: output/data/data_cohort.rds
      moderately_sensitive:
        flow: output/data/flowchart.csv

  descr_table1:
    run: r:latest analysis/descriptive/table1.R
    needs: [design, data_selection]
    outputs:
      moderately_sensitive:
        html: output/descriptive/tables/table1.html
        csv: output/descriptive/tables/table1.csv

#######################################
 ## MATCHING
#######################################

  # data_selection:
  #   run: r:latest analysis/process/data_selection.R
  #   needs: [data_process]
  #   outputs:
  #     highly_sensitive:
  #       data_az: output/data/data_vax_az_withoutdate.csv
  #       data_pfizer: output/data/data_vax_pfizer_withoutdate.csv
  #       data_az_date: output/data/data_vax_az_withdate.csv
  #       data_pfizer_date: output/data/data_vax_pfizer_withdate.csv
  #
  # matchwithoutdate_recipients:
  #   run: python:latest python analysis/matching/matchwithoutdate.py
  #   needs: [data_selection]
  #   outputs:
  #     highly_sensitive:
  #       cases: output/data/matched_cases_withoutdate.csv
  #       matches: output/data/matched_matches_withoutdate.csv
  #       combined: output/data/matched_combined_withoutdate.csv
  #     moderately_sensitive:
  #       report: output/data/matching_report_withoutdate.txt
  #
  # matchwithoutdate_process:
  #   run: r:latest analysis/matching/match_process.R withoutdate
  #   needs: [design, matchwithoutdate_recipients, data_selection]
  #   outputs:
  #     highly_sensitive:
  #       data: output/data/data_matches_withoutdate.rds
  #     moderately_sensitive:
  #       report: output/matching/matching_balance_withoutdate.html
  #
  #
  # matchwithdate_recipients:
  #   run: python:latest python analysis/matching/matchwithdate.py
  #   needs: [data_selection]
  #   outputs:
  #     highly_sensitive:
  #       cases: output/data/matched_cases_withdate.csv
  #       matches: output/data/matched_matches_withdate.csv
  #       combined: output/data/matched_combined_withdate.csv
  #     moderately_sensitive:
  #       report: output/data/matching_report_withdate.txt
  #
  #
  # matchwithdate_process:
  #   run: r:latest analysis/matching/match_process.R withdate
  #   needs: [design, matchwithdate_recipients, data_selection]
  #   outputs:
  #     highly_sensitive:
  #       data: output/data/data_matches_withdate.rds
  #     moderately_sensitive:
  #       report: output/matching/matching_balance_withdate.html



#######################################
 ## COMPARATIVE EFFECTIVENESS MODELS
 ## positive test outcome
#######################################

  model_calendar_postest:
    run: r:latest analysis/models/model_cox_calendar.R postest
    needs: [design, data_selection]
    outputs:
      highly_sensitive:
        data: output/postest/data_cox_split.rds
        models: output/postest/model*.rds
      moderately_sensitive:
        logs:  output/postest/log*.txt

  report_calendar_postest:
    run: r:latest analysis/models/report_cox.R postest
    needs: [design, model_calendar_postest]
    outputs:
      moderately_sensitive:
        figure: output/postest/forest*.svg
        table: output/postest/estimates*.csv

  model_calendar_covidadmitted:
    run: r:latest analysis/models/model_cox_calendar.R covidadmitted
    needs: [design, data_selection]
    outputs:
      highly_sensitive:
        data: output/covidadmitted/data_cox_split.rds
        models: output/covidadmitted/model*.rds
      moderately_sensitive:
        logs:  output/covidadmitted/log*.txt

  report_calendar_covidadmitted:
    run: r:latest analysis/models/report_cox.R covidadmitted
    needs: [design, model_calendar_covidadmitted]
    outputs:
      moderately_sensitive:
        figure: output/covidadmitted/forest*.svg
        table: output/covidadmitted/estimates*.csv

  model_calendar_coviddeath:
    run: r:latest analysis/models/model_cox_calendar.R coviddeath
    needs: [design, data_selection]
    outputs:
      highly_sensitive:
        data: output/coviddeath/data_cox_split.rds
        models: output/coviddeath/model*.rds
      moderately_sensitive:
        logs:  output/coviddeath/log*.txt

  report_calendar_coviddeath:
    run: r:latest analysis/models/report_cox.R coviddeath
    needs: [design, model_calendar_coviddeath]
    outputs:
      moderately_sensitive:
        figure: output/coviddeath/forest*.svg
        table: output/coviddeath/estimates*.csv

