version: '3.0'

expectations:

  population_size: 100000

actions:

  ## # # # # # # # # # # # # # # # # # # # 
  ## Temp second dose info 
  ## # # # # # # # # # # # # # # # # # # # 

  seconddose_extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2dose
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_2dose.feather

  seconddose_process:
    run: r:latest analysis/seconddose/process.R
    needs:
    - seconddose_extract
    outputs:
      highly_sensitive:
        data: output/data/seconddose_data_processed.rds

  seconddose_graphs:
    run: r:latest analysis/seconddose/graphs.R
    needs:
    - seconddose_process
    outputs:
      moderately_sensitive:
        data: output/seconddose/plots/plot*.png

  ## # # # # # # # # # # # # # # # # # # # 
  ## HCW characteristics 
  ## # # # # # # # # # # # # # # # # # # # 

  hcw_extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hcw
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_hcw.feather

  hcw_process:
    run: r:latest analysis/hcw/process.R
    needs:
    - hcw_extract
    outputs:
      highly_sensitive:
        data: output/data/hcw_data_processed.rds
        datavax: output/data/hcw_data_vax.rds

  hcw_properties:
    run: r:latest analysis/process/data_properties.R output/data/hcw_data_processed.rds
      output/data_properties
    needs:
    - hcw_process
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/hcw_data_processed*.txt

  hcw_descr:
    run: r:latest analysis/hcw/descr.R
    needs:
    - hcw_process
    outputs:
      moderately_sensitive:
        png: output/hcw/*.png
        svg: output/hcw/*.svg
        html: output/hcw/*.html
        csv: output/hcw/*.csv

  ## # # # # # # # # # # # # # # # # # # # 
  ## Extract and process 
  ## # # # # # # # # # # # # # # # # # # # 

  design:
    run: r:latest analysis/process/design.R
    outputs:
      moderately_sensitive:
        metadata: output/data/metadata*

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  data_process:
    run: r:latest analysis/process/data_process.R
    needs:
    - extract
    outputs:
      highly_sensitive:
        cohort: output/data/data_processed.rds

  data_properties:
    run: r:latest analysis/process/data_properties.R output/data/data_processed.rds
      output/data_properties
    needs:
    - data_process
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt

  data_selection:
    run: r:latest analysis/process/data_selection.R
    needs:
    - data_process
    outputs:
      highly_sensitive:
        data_allvax: output/data/data_cohort_allvax.rds
        data: output/data/data_cohort.rds
      moderately_sensitive:
        flow: output/data/flowchart.csv

  ## # # # # # # # # # # # # # # # # # # # 
  ## Descriptive stats 
  ## # # # # # # # # # # # # # # # # # # # 

  descr_table1:
    run: r:latest analysis/descriptive/table1.R
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/descriptive/tables/table1*.rds
      moderately_sensitive:
        html: output/descriptive/tables/table1*.html
        csv: output/descriptive/tables/table1*.csv

  descr_table1_allvax:
    run: r:latest analysis/descriptive/table1_allvax.R
    needs:
    - design
    - data_selection
    outputs:
      moderately_sensitive:
        html: output/descriptive/tables/table1_allvax.html
        csv: output/descriptive/tables/table1_allvax.csv

  descr_irr:
    run: r:latest analysis/descriptive/table_irr.R output/data/data_processed.rds
      output/data_properties
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/descriptive/tables/table_irr.rds
      moderately_sensitive:
        html: output/descriptive/tables/table_irr.html
        csv: output/descriptive/tables/table_irr.csv

  descr_km:
    run: r:latest analysis/descriptive/km.R output/data/data_processed.rds output/data_properties
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/descriptive/km/plot_survival*.rds
      moderately_sensitive:
        png: output/descriptive/km/plot_survival*.png
        svg: output/descriptive/km/plot_survival*.svg

  ## # # # # # # # # # # # # # # # # # # # 
  ## Models 
  ## # # # # # # # # # # # # # # # # # # # 
  ## ###  SARS-CoV-2 Test 

  model_test_timesincevax_cox:
    run: r:latest analysis/models/model_cox.R test timesincevax
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/test/timesincevax/modelcox*.rds
      moderately_sensitive:
        txt: output/models/test/timesincevax/modelcox*.txt
        csv: output/models/test/timesincevax/modelcox*.csv

  report_test_timesincevax_cox:
    run: r:latest analysis/models/report_cox.R test timesincevax
    needs:
    - design
    - model_test_timesincevax_cox
    outputs:
      highly_sensitive:
        rds: output/models/test/timesincevax/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/test/timesincevax/reportcox_*.csv
        svg: output/models/test/timesincevax/reportcox_*.svg
        png: output/models/test/timesincevax/reportcox_*.png

  model_test_calendar_cox:
    run: r:latest analysis/models/model_cox.R test calendar
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/test/calendar/modelcox*.rds
      moderately_sensitive:
        txt: output/models/test/calendar/modelcox*.txt
        csv: output/models/test/calendar/modelcox*.csv

  report_test_calendar_cox:
    run: r:latest analysis/models/report_cox.R test calendar
    needs:
    - design
    - model_test_calendar_cox
    outputs:
      highly_sensitive:
        rds: output/models/test/calendar/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/test/calendar/reportcox_*.csv
        svg: output/models/test/calendar/reportcox_*.svg
        png: output/models/test/calendar/reportcox_*.png

  model_test_timesincevax_plr:
    run: r:latest analysis/models/model_plr.R test timesincevax 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/test/timesincevax/modelplr*.rds
      moderately_sensitive:
        txt: output/models/test/timesincevax/modelplr*.txt
        csv: output/models/test/timesincevax/modelplr*.csv

  report_test_timesincevax_plr:
    run: r:latest analysis/models/report_plr.R test timesincevax
    needs:
    - design
    - model_test_timesincevax_plr
    outputs:
      highly_sensitive:
        rds: output/models/test/timesincevax/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/test/timesincevax/reportplr_*.csv
        svg: output/models/test/timesincevax/reportplr_*.svg
        png: output/models/test/timesincevax/reportplr_*.png

  model_test_calendar_plr:
    run: r:latest analysis/models/model_plr.R test calendar 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/test/calendar/modelplr*.rds
      moderately_sensitive:
        txt: output/models/test/calendar/modelplr*.txt
        csv: output/models/test/calendar/modelplr*.csv

  report_test_calendar_plr:
    run: r:latest analysis/models/report_plr.R test calendar
    needs:
    - design
    - model_test_calendar_plr
    outputs:
      highly_sensitive:
        rds: output/models/test/calendar/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/test/calendar/reportplr_*.csv
        svg: output/models/test/calendar/reportplr_*.svg
        png: output/models/test/calendar/reportplr_*.png

  ## ###  Positive SARS-CoV-2 Test 

  model_postest_timesincevax_cox:
    run: r:latest analysis/models/model_cox.R postest timesincevax
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/postest/timesincevax/modelcox*.rds
      moderately_sensitive:
        txt: output/models/postest/timesincevax/modelcox*.txt
        csv: output/models/postest/timesincevax/modelcox*.csv

  report_postest_timesincevax_cox:
    run: r:latest analysis/models/report_cox.R postest timesincevax
    needs:
    - design
    - model_postest_timesincevax_cox
    outputs:
      highly_sensitive:
        rds: output/models/postest/timesincevax/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/postest/timesincevax/reportcox_*.csv
        svg: output/models/postest/timesincevax/reportcox_*.svg
        png: output/models/postest/timesincevax/reportcox_*.png

  model_postest_calendar_cox:
    run: r:latest analysis/models/model_cox.R postest calendar
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/postest/calendar/modelcox*.rds
      moderately_sensitive:
        txt: output/models/postest/calendar/modelcox*.txt
        csv: output/models/postest/calendar/modelcox*.csv

  report_postest_calendar_cox:
    run: r:latest analysis/models/report_cox.R postest calendar
    needs:
    - design
    - model_postest_calendar_cox
    outputs:
      highly_sensitive:
        rds: output/models/postest/calendar/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/postest/calendar/reportcox_*.csv
        svg: output/models/postest/calendar/reportcox_*.svg
        png: output/models/postest/calendar/reportcox_*.png

  model_postest_timesincevax_plr:
    run: r:latest analysis/models/model_plr.R postest timesincevax 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/postest/timesincevax/modelplr*.rds
      moderately_sensitive:
        txt: output/models/postest/timesincevax/modelplr*.txt
        csv: output/models/postest/timesincevax/modelplr*.csv

  report_postest_timesincevax_plr:
    run: r:latest analysis/models/report_plr.R postest timesincevax
    needs:
    - design
    - model_postest_timesincevax_plr
    outputs:
      highly_sensitive:
        rds: output/models/postest/timesincevax/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/postest/timesincevax/reportplr_*.csv
        svg: output/models/postest/timesincevax/reportplr_*.svg
        png: output/models/postest/timesincevax/reportplr_*.png

  model_postest_calendar_plr:
    run: r:latest analysis/models/model_plr.R postest calendar 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/postest/calendar/modelplr*.rds
      moderately_sensitive:
        txt: output/models/postest/calendar/modelplr*.txt
        csv: output/models/postest/calendar/modelplr*.csv

  report_postest_calendar_plr:
    run: r:latest analysis/models/report_plr.R postest calendar
    needs:
    - design
    - model_postest_calendar_plr
    outputs:
      highly_sensitive:
        rds: output/models/postest/calendar/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/postest/calendar/reportplr_*.csv
        svg: output/models/postest/calendar/reportplr_*.svg
        png: output/models/postest/calendar/reportplr_*.png

  ## ###  A&E attendence 

  model_emergency_timesincevax_cox:
    run: r:latest analysis/models/model_cox.R emergency timesincevax
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/emergency/timesincevax/modelcox*.rds
      moderately_sensitive:
        txt: output/models/emergency/timesincevax/modelcox*.txt
        csv: output/models/emergency/timesincevax/modelcox*.csv

  report_emergency_timesincevax_cox:
    run: r:latest analysis/models/report_cox.R emergency timesincevax
    needs:
    - design
    - model_emergency_timesincevax_cox
    outputs:
      highly_sensitive:
        rds: output/models/emergency/timesincevax/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/emergency/timesincevax/reportcox_*.csv
        svg: output/models/emergency/timesincevax/reportcox_*.svg
        png: output/models/emergency/timesincevax/reportcox_*.png

  model_emergency_calendar_cox:
    run: r:latest analysis/models/model_cox.R emergency calendar
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/emergency/calendar/modelcox*.rds
      moderately_sensitive:
        txt: output/models/emergency/calendar/modelcox*.txt
        csv: output/models/emergency/calendar/modelcox*.csv

  report_emergency_calendar_cox:
    run: r:latest analysis/models/report_cox.R emergency calendar
    needs:
    - design
    - model_emergency_calendar_cox
    outputs:
      highly_sensitive:
        rds: output/models/emergency/calendar/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/emergency/calendar/reportcox_*.csv
        svg: output/models/emergency/calendar/reportcox_*.svg
        png: output/models/emergency/calendar/reportcox_*.png

  model_emergency_timesincevax_plr:
    run: r:latest analysis/models/model_plr.R emergency timesincevax 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/emergency/timesincevax/modelplr*.rds
      moderately_sensitive:
        txt: output/models/emergency/timesincevax/modelplr*.txt
        csv: output/models/emergency/timesincevax/modelplr*.csv

  report_emergency_timesincevax_plr:
    run: r:latest analysis/models/report_plr.R emergency timesincevax
    needs:
    - design
    - model_emergency_timesincevax_plr
    outputs:
      highly_sensitive:
        rds: output/models/emergency/timesincevax/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/emergency/timesincevax/reportplr_*.csv
        svg: output/models/emergency/timesincevax/reportplr_*.svg
        png: output/models/emergency/timesincevax/reportplr_*.png

  model_emergency_calendar_plr:
    run: r:latest analysis/models/model_plr.R emergency calendar 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/emergency/calendar/modelplr*.rds
      moderately_sensitive:
        txt: output/models/emergency/calendar/modelplr*.txt
        csv: output/models/emergency/calendar/modelplr*.csv

  report_emergency_calendar_plr:
    run: r:latest analysis/models/report_plr.R emergency calendar
    needs:
    - design
    - model_emergency_calendar_plr
    outputs:
      highly_sensitive:
        rds: output/models/emergency/calendar/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/emergency/calendar/reportplr_*.csv
        svg: output/models/emergency/calendar/reportplr_*.svg
        png: output/models/emergency/calendar/reportplr_*.png

  ## ###  COVID-19 hospital admission 

  model_covidadmitted_timesincevax_cox:
    run: r:latest analysis/models/model_cox.R covidadmitted timesincevax
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/timesincevax/modelcox*.rds
      moderately_sensitive:
        txt: output/models/covidadmitted/timesincevax/modelcox*.txt
        csv: output/models/covidadmitted/timesincevax/modelcox*.csv

  report_covidadmitted_timesincevax_cox:
    run: r:latest analysis/models/report_cox.R covidadmitted timesincevax
    needs:
    - design
    - model_covidadmitted_timesincevax_cox
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/timesincevax/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/covidadmitted/timesincevax/reportcox_*.csv
        svg: output/models/covidadmitted/timesincevax/reportcox_*.svg
        png: output/models/covidadmitted/timesincevax/reportcox_*.png

  model_covidadmitted_calendar_cox:
    run: r:latest analysis/models/model_cox.R covidadmitted calendar
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/calendar/modelcox*.rds
      moderately_sensitive:
        txt: output/models/covidadmitted/calendar/modelcox*.txt
        csv: output/models/covidadmitted/calendar/modelcox*.csv

  report_covidadmitted_calendar_cox:
    run: r:latest analysis/models/report_cox.R covidadmitted calendar
    needs:
    - design
    - model_covidadmitted_calendar_cox
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/calendar/reportcox_*.rds
      moderately_sensitive:
        csv: output/models/covidadmitted/calendar/reportcox_*.csv
        svg: output/models/covidadmitted/calendar/reportcox_*.svg
        png: output/models/covidadmitted/calendar/reportcox_*.png

  model_covidadmitted_timesincevax_plr:
    run: r:latest analysis/models/model_plr.R covidadmitted timesincevax 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/timesincevax/modelplr*.rds
      moderately_sensitive:
        txt: output/models/covidadmitted/timesincevax/modelplr*.txt
        csv: output/models/covidadmitted/timesincevax/modelplr*.csv

  report_covidadmitted_timesincevax_plr:
    run: r:latest analysis/models/report_plr.R covidadmitted timesincevax
    needs:
    - design
    - model_covidadmitted_timesincevax_plr
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/timesincevax/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/covidadmitted/timesincevax/reportplr_*.csv
        svg: output/models/covidadmitted/timesincevax/reportplr_*.svg
        png: output/models/covidadmitted/timesincevax/reportplr_*.png

  model_covidadmitted_calendar_plr:
    run: r:latest analysis/models/model_plr.R covidadmitted calendar 50000
    needs:
    - design
    - data_selection
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/calendar/modelplr*.rds
      moderately_sensitive:
        txt: output/models/covidadmitted/calendar/modelplr*.txt
        csv: output/models/covidadmitted/calendar/modelplr*.csv

  report_covidadmitted_calendar_plr:
    run: r:latest analysis/models/report_plr.R covidadmitted calendar
    needs:
    - design
    - model_covidadmitted_calendar_plr
    outputs:
      highly_sensitive:
        rds: output/models/covidadmitted/calendar/reportplr_*.rds
      moderately_sensitive:
        csv: output/models/covidadmitted/calendar/reportplr_*.csv
        svg: output/models/covidadmitted/calendar/reportplr_*.svg
        png: output/models/covidadmitted/calendar/reportplr_*.png

  rmd_report:
    run: r:latest -e 'rmarkdown::render("analysis/report/effectiveness_report.Rmd",
      knit_root_dir = "/workspace", output_dir="/workspace/output")'
    needs:
    - design
    - data_selection
    - descr_table1
    - descr_irr
    - descr_km
    - report_test_timesincevax_cox
    - report_test_calendar_cox
    - report_postest_timesincevax_cox
    - report_postest_calendar_cox
    - report_emergency_timesincevax_cox
    - report_emergency_calendar_cox
    - report_covidadmitted_timesincevax_cox
    - report_covidadmitted_calendar_cox
    outputs:
      moderately_sensitive:
        html: output/effectiveness_report.html

